=== cai880210/iif-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:string"/>
	<xs:element name="os">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="installation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="os" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="installation"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployref">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
			<xs:attribute name="default" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployref" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deployto"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="sid" type="xs:string" use="required"/>
            <xs:attribute name="contextpathprefix" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="path" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
         <xs:complexType name="InOut">
              <xs:sequence>
                 <xs:element ref="Datatype"/>
                 <xs:element ref="Required" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="CliMapping" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="Documentation" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="OutFileName" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:attribute name="name" type="xs:string" use="required"/>
           </xs:complexType>
          <xs:complexType name="Input">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                  <xs:element ref="Default" minOccurs="0" maxOccurs="1"/>
                  <xs:element ref="Restriction" minOccurs="0" maxOccurs="1"/>
               </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
          <xs:complexType name="Output">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Extension" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="OutfileId" type="xs:string" default="false" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
    <xs:element name="input" type="Input"/>
    <xs:element name="output" type="Output"/>

<!--	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Restriction" minOccurs="0"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping" minOccurs="0"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
        </xs:element>
        <xs:element name="output">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="Datatype"/>
                    <xs:element ref="CliMapping"/>
                    <xs:element ref="Required"/>
                    <xs:element ref="Documentation"/>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0"/>
                    <xs:element name="Extension" type="xs:string"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:complexType>
        </xs:element>-->

	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
				<xs:element ref="path"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Restriction">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Value" maxOccurs="unbounded"/>
			</xs:sequence>
                        <xs:attribute name="multiple" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
                                <xs:element name="toolsbasedir" type="xs:string"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
        <xs:element name="Default">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="clireplacement" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Datatype" type="xs:string"/>
    <xs:element name="CliMapping" type="xs:string"/>
    <xs:element name="OutFileName" type="xs:string"/>
</xs:schema>

=== cai880210/iif-toolwrapper/examples/xsltproc.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>xsltproc</id>
    <name>XSLT Processor</name>
    <homepage>http://xmlsoft.org/XSLT/xsltproc.html</homepage>
    <version></version>
    <installation>
        <os type="linux">
            Available under most distributions via package management.
        </os>
        <os type="windows">
            Binaries for Windows are available from the project homepage. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
    </installation>
    <services>
        <service sid="1" name="XSLTProc" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for transforming XML documents using XSLT</description>
            <operations>
                <operation oid="1" name="xsltproc">
                    <description>Transform XML using XSLT</description>
                    <!--
                    Usage:
                    xsltproc [options] <stylesheet> <document>

                    Where:
		            <stylesheet> 	XSL stylesheet
		            <document> 		XML input document
                    [options] 		optional command line parameters
                    -->
                    <command>xsltproc -o ${output} ${stylesheet} ${document}</command>
                    <inputs>
                        <input name="stylesheet">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>stylesheet</CliMapping>
                            <Documentation>URL reference to XSL stylesheet</Documentation>
                            <Default>http://github.com/impactcentre/iif-testfiles/raw/master/testfiles/stylesheet.xsl</Default>
                        </input>
                        <input name="document">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>document</CliMapping>
                            <Documentation>URL reference to XML document</Documentation>
                            <Default>http://github.com/impactcentre/iif-testfiles/raw/master/testfiles/document.xml</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to transformed XML document</Documentation>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/default-toolspec.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/main/resources/toolspec.xsd">
    <id>copy</id>
    <name>Copy</name>
    <homepage>http://en.wikipedia.org/wiki/Cp_%28Unix%29</homepage>
    <version>1.0</version>
    <installation>
        <os type="linux">
            Available by default.
        </os>
        <os type="windows">
            Use "CMD.exe /C COPY" instead of "/bin/cp" in the commands defined below.
        </os>
    </installation>
    <services>
        <service sid="1" name="Simple Copy" type="migrate" servicepackage="eu.impact_project.iif.services" contextpathprefix="/impactservices">
            <description>Service for copying files</description>
            <operations>
                <operation oid="1" name="simpleCopy">
                    <description>Copies a file</description>
                    <command>/bin/cp ${input} ${output}</command>
                    <inputs>
                        <input name="inputUrl">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://localhost:8080/test.txt</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <PrefixFromInput>input</PrefixFromInput>
                            <Extension>txt</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
		        <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>src/main/webapp/</accessdir>
                <accessurl>http://localhost:8080/impactservices/impact-simplecopy10-service/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/gppbinarisation.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>gppbinarisation</id>
    <name>NCSR GPP Binarisation</name>
    <homepage>http://www.digitisation.eu/tools/browse/image-enhancement/binarisation-and-colour-reduction/ncsr-binarisation/</homepage>
    <version></version>
    <installation>
        <os type="linux">
            Not currently supported.
        </os>
        <os type="windows">
            Requires installation of the NCSR GPP Binarisation Toolkit. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
    </installation>
    <services>
        <service sid="1" name="GPPBinarisation" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for document image binarisation using GPP algorithm</description>
            <operations>
                <operation oid="1" name="gppBinarise">
                    <description>Binarise document image using GPP algorithm</description>
                    <!--
                    Usage:
                    gpp.exe <in> <out>

                    Where:
                    <in>    Input image file in TIF format
                    <out>   Bitonal output image file
                    -->
                    <command>gpp.exe ${input} ${output}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to image file in TIF format</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.tif</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to bitonal output image file</Documentation>
                            <Extension>tif</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir>C:\\GPPBIN\\</toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/ocrad.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>ocrad</id>
    <name>Ocrad</name>
    <homepage>http://www.gnu.org/s/ocrad/</homepage>
    <version>0-17</version>
    <installation>
        <os type="linux">
            Available under most distributions via package management.
        </os>
        <os type="windows">
            Not currently supported.
        </os>
    </installation>
    <services>
        <service sid="1" name="Ocrad" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for text recognition using GNU Ocrad</description>
            <operations>
                <operation oid="1" name="ocrad">
                    <description>Perform text recognition using ocrad</description>
                    <!--
                    Usage: 
                    ocrad [options] <input>

                    Where:
                    [options]
                    -h, - - help               	display this help and exit
                    -V, - - version            	output version information and exit
                    -a, - - append             	append text to output file
                    -b, - - block=<n>          	process only the specified text block
                    -c, - - charset=<name>     	try `- - charset=help' for a list of names
                    -e, - - filter=<name>      	try `- - filter=help' for a list of names
                    -f, - - force              	force overwrite of output file
                    -F, - - format=<fmt>       	output format (byte, utf8)
                    -i, - - invert             	invert image levels (white on black)
                    -l, - - layout=<n>         	layout analysis, 0=none, 1=column, 2=full
                    -o <file>                	place the output into <file>
                    -p, - - crop=<l,t,r,b>     	crop input image by given rectangle
                    -s, - - scale=[-]<n>       	scale input image by [1/]<n>
                    -t, - - transform=<name>   	try `- - transform=help' for a list of names
                    -T, - - threshold=<n%>     	threshold for binarization (0-100%)
                    -v, - - verbose            	be verbose
                    -x <file>                	export OCR Results File to <file>
                    <input>			            path to input image file(s)

                    For full documentation of ocrad command line parameters, see
                    http://www.gnu.org/software/ocrad/manual/ocrad_manual.html
                    -->
                    <command>ocrad --format=utf8 --force --layout --output=${output} --export=${result} ${input}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to image file in PBM, PGM or PPM format</Documentation>
                            <Default>http://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.pgm</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <Extension>txt</Extension>
                        </output>
                        <output name="result">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>result</CliMapping>
                            <Documentation>URL reference to result file</Documentation>
                            <Extension>orf</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
