=== cai880210/iif-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:string"/>
	<xs:element name="os">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="installation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="os" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="installation"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployref">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
			<xs:attribute name="default" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployref" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deployto"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="sid" type="xs:string" use="required"/>
            <xs:attribute name="contextpathprefix" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="path" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
         <xs:complexType name="InOut">
              <xs:sequence>
                 <xs:element ref="Datatype"/>
                 <xs:element ref="Required" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="CliMapping" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="Documentation" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="OutFileName" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:attribute name="name" type="xs:string" use="required"/>
           </xs:complexType>
          <xs:complexType name="Input">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                  <xs:element ref="Default" minOccurs="0" maxOccurs="1"/>
                  <xs:element ref="Restriction" minOccurs="0" maxOccurs="1"/>
               </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
          <xs:complexType name="Output">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Extension" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="OutfileId" type="xs:string" default="false" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
    <xs:element name="input" type="Input"/>
    <xs:element name="output" type="Output"/>

<!--	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Restriction" minOccurs="0"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping" minOccurs="0"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
        </xs:element>
        <xs:element name="output">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="Datatype"/>
                    <xs:element ref="CliMapping"/>
                    <xs:element ref="Required"/>
                    <xs:element ref="Documentation"/>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0"/>
                    <xs:element name="Extension" type="xs:string"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:complexType>
        </xs:element>-->

	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
				<xs:element ref="path"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Restriction">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Value" maxOccurs="unbounded"/>
			</xs:sequence>
                        <xs:attribute name="multiple" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
                                <xs:element name="toolsbasedir" type="xs:string"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
        <xs:element name="Default">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="clireplacement" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Datatype" type="xs:string"/>
    <xs:element name="CliMapping" type="xs:string"/>
    <xs:element name="OutFileName" type="xs:string"/>
</xs:schema>

=== cai880210/iif-toolwrapper/examples/tesseract.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>tesseract</id>
    <name>Tesseract OCR</name>
    <homepage>http://code.google.com/p/tesseract-ocr/</homepage>
    <version>3-0-2</version>
    <installation>
        <os type="linux">
            Available under most distributions via package management.
        </os>
        <os type="windows">
            Binaries for Windows are available from the project homepage. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
    </installation>
    <services>
        <service sid="1" name="Tesseract" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for text recognition using Tesseract</description>
            <operations>
                <operation oid="1" name="tesseract">
                    <description>Perform text recognition on image file</description>
                    <!--
                    Usage:
                    tesseract[.exe] <input> <output> -l <lang> [+hocr]

                    Where:
                    <input> 	Input image file in TIF format
                    <output> 	OCR result file in TXT format
                    <lang> 	    Language model used for recognition
                    [+hocr] 	Optional: write hOCR output file (with coordinates)
                    -->
                    <command>tesseract ${input} ${output} -l ${langmod}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.bw.tif</Default>
                        </input>
                        <input name="langmod">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>langmod</CliMapping>
                            <Documentation>Language module used by Tesseract</Documentation>
                            <Default>deu-frak</Default>
                            <Restriction>
                                <Value>afr</Value>
                                <Value>ara</Value>
                                <Value>aze</Value>
                                <Value>bel</Value>
                                <Value>ben</Value>
                                <Value>bul</Value>
                                <Value>cat</Value>
                                <Value>ces</Value>
                                <Value>chi_sim</Value>
                                <Value>chi_tra</Value>
                                <Value>chr</Value>
                                <Value>dan</Value>
                                <Value>dan-frak</Value>
                                <Value>deu</Value>
                                <Value>deu-frak</Value>
                                <Value>ell</Value>
                                <Value>eng</Value>
                                <Value>enm</Value>
                                <Value>epo</Value>
                                <Value>equ</Value>
                                <Value>est</Value>
                                <Value>eus</Value>
                                <Value>fin</Value>
                                <Value>fra</Value>
                                <Value>frk</Value>
                                <Value>frm</Value>
                                <Value>glg</Value>
                                <Value>grc</Value>
                                <Value>heb</Value>
                                <Value>hin</Value>
                                <Value>hrv</Value>
                                <Value>hun</Value>
                                <Value>ind</Value>
                                <Value>isl</Value>
                                <Value>ita</Value>
                                <Value>ita-old</Value>
                                <Value>jpn</Value>
                                <Value>kan</Value>
                                <Value>kor</Value>
                                <Value>lat-lid</Value>
                                <Value>lav</Value>
                                <Value>lit</Value>
                                <Value>mal</Value>
                                <Value>mkd</Value>
                                <Value>mlt</Value>
                                <Value>msa</Value>
                                <Value>nld</Value>
                                <Value>nor</Value>
                                <Value>osd</Value>
                                <Value>pol</Value>
                                <Value>por</Value>
                                <Value>ron</Value>
                                <Value>rus</Value>
                                <Value>slk</Value>
                                <Value>slk-frak</Value>
                                <Value>slv</Value>
                                <Value>spa</Value>
                                <Value>spa-old</Value>
                                <Value>srp</Value>
                                <Value>swe</Value>
                                <Value>swe-frak</Value>
                                <Value>tha</Value>
                                <Value>tgl</Value>
                                <Value>tur</Value>
                                <Value>ukr</Value>
                                <Value>vie</Value>
                            </Restriction>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <Extension>txt</Extension>
                            <AutoExtension>true</AutoExtension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir>C:\\TESSOCR\\</toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/jp2convert.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>jp2convert</id>
    <name>OpenJPEG JPEG2000 Converter</name>
    <homepage>http://www.openjpeg.org/</homepage>
    <version></version>
    <installation>
        <os type="linux">
            Available under most distributions via package management.
        </os>
        <os type="windows">
            Binaries for Windows are available from the project homepage. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
    </installation>
    <services>
        <service sid="1" name="jp2convert" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Service for converting JPEG2000 images to other image file formats</description>
            <operations>
                <operation oid="1" name="jp2convert">
                    <description>Convert JPEG2000 image file</description>
                    <!--
                    Usage:
                    j2k_to_image -i <input> -o <output> -OutFor <format>

                    Where:
                    <input>     Input file; valid image extensions are J2K, JP2, JPC, JPT
                    <output>    Output file
                    <format>    Output format; currently accepts BMP, TIF, RAW, TGA, PGM, PPM, PNM and PGX
                    -->
                    <command>j2k_to_image -i ${input} -o ${output} -OutFor ${format}</command>
                    <inputs>
                        <input name="format">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>format</CliMapping>
                            <Documentation>Output image file format</Documentation>
                            <Default>TIF</Default>
                            <Restriction>
                                <Value>BMP</Value>
                                <Value>TIF</Value>
                                <Value>RAW</Value>
                                <Value>TGA</Value>
                                <Value>PGM</Value>
                                <Value>PBM</Value>
                                <Value>PNM</Value>
                                <Value>PGX</Value>
                            </Restriction>
                        </input>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to JPEG2000 image file</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.jp2</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output image file</Documentation>
                            <Extension>tif</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/namedentitiesrecognizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>namedentitiesrecognizer</id>
    <name>INL Named Entities Recognition Tool</name>
    <homepage>http://www.digitisation.eu/tools/browse/toolbox-for-lexicon-building/named-entities-recognition-tool-nert/</homepage>
    <version>2-3</version>
    <installation>
        <os type="linux">
            Fully supported through Java.
        </os>
        <os type="windows">
            Fully supported through Java.
        </os>
    </installation>
    <services>
        <service sid="1" name="NamedEntitiesRecognizer" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>The service can retrieve named entities (persons, locations and organizations) from a text file. It uses a supervised learning technique, which means it has to be trained with a manually tagged trainfile before it is applied to other text.</description>
            <operations>
                <operation oid="1" name="recognizeNE">
                    <description>Retrieve named entities (persons, locations and organizations) from a text file</description>
                    <!--
                    Usage:
                    java -jar nert.jar -e -loadClassifier <model> -testfile <testfile> -in <in> -out <out>

                    Where:
                    <model>     Trained model for the text
                    <testfile>  Input file to be analysed
                    <in>        Input file format
                    <out>       Output file format
                    -->
                    <command>java -jar ./nert/nert.jar -e -loadClassifier ./nert/data/models/${modelfile} -testfile ${infile} -in txt -out txt</command>
                    <inputs>
                        <input name="modelfile">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>modelfile</CliMapping>
                            <Documentation>URL reference to text file</Documentation>
                            <Default>dpo35_minpp56-65_ocr.ser.gz</Default>
                            <Restriction>
                                <Value>dpo35_minpp56-65_ocr.ser.gz</Value>
                                <Value>sg20_min19291930_ocr.ser.gz</Value>
                            </Restriction>
                        </input>
                        <input name="infile">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>infile</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/nld.ocr.txt</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="outfile">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outfile</CliMapping>
                            <Documentation>URL reference to annotated output text file</Documentation>
                            <Extension>xml</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
	        Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
