=== cai880210/iif-toolwrapper/src/main/resources/toolspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="version" type="xs:string"/>
	<xs:element name="os">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="installation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="os" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="user" type="xs:string"/>
	<xs:element name="toolspec">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="homepage"/>
				<xs:element ref="version"/>
				<xs:element ref="installation"/>
				<xs:element ref="services"/>
				<xs:element ref="deployments"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployref">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:IDREF"/>
			<xs:attribute name="default" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployref" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="operations"/>
				<xs:element ref="deployto"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="servicepackage" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="sid" type="xs:string" use="required"/>
            <xs:attribute name="contextpathprefix" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ports">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="port" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="port">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:int">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="password" type="xs:string"/>
	<xs:element name="path" type="xs:string"/>
	<xs:element name="outputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="output" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
         <xs:complexType name="InOut">
              <xs:sequence>
                 <xs:element ref="Datatype"/>
                 <xs:element ref="Required" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="CliMapping" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="Documentation" minOccurs="0" maxOccurs="1"/>
                 <xs:element ref="OutFileName" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
              <xs:attribute name="name" type="xs:string" use="required"/>
           </xs:complexType>
          <xs:complexType name="Input">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                  <xs:element ref="Default" minOccurs="0" maxOccurs="1"/>
                  <xs:element ref="Restriction" minOccurs="0" maxOccurs="1"/>
               </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
          <xs:complexType name="Output">
            <xs:complexContent>
             <xs:extension base="InOut">
               <xs:sequence>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="Extension" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="OutfileId" type="xs:string" default="false" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
             </xs:extension>
            </xs:complexContent>
          </xs:complexType>
    <xs:element name="input" type="Input"/>
    <xs:element name="output" type="Output"/>

<!--	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Datatype"/>
				<xs:element ref="Restriction" minOccurs="0"/>
				<xs:element ref="Required"/>
				<xs:element ref="Default"/>
				<xs:element ref="CliMapping" minOccurs="0"/>
				<xs:element ref="Documentation"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
        </xs:element>
        <xs:element name="output">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="Datatype"/>
                    <xs:element ref="CliMapping"/>
                    <xs:element ref="Required"/>
                    <xs:element ref="Documentation"/>
                    <xs:element name="PrefixFromInput" type="xs:string" minOccurs="0"/>
                    <xs:element name="Extension" type="xs:string"/>
                    <xs:element name="AutoExtension" type="xs:boolean" default="false" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:complexType>
        </xs:element>-->

	<xs:element name="operations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="command"/>
				<xs:element ref="inputs"/>
				<xs:element ref="outputs"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="oid" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="manager">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user"/>
				<xs:element ref="password"/>
				<xs:element ref="path"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="input" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Restriction">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="Value" maxOccurs="unbounded"/>
			</xs:sequence>
                        <xs:attribute name="multiple" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="identifier" type="xs:string"/>
	<xs:element name="id" type="xs:ID"/>
	<xs:element name="host" type="xs:string"/>
	<xs:element name="homepage" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="deployments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployment" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="deployment">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="identifier"/>
				<xs:element ref="host"/>
				<xs:element ref="ports"/>
				<xs:element ref="manager"/>
                                <xs:element name="toolsbasedir" type="xs:string"/>
				<xs:element ref="dataexchange"/>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:string"/>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dataexchange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="accessdir"/>
				<xs:element ref="accessurl"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="command" type="xs:string"/>
	<xs:element name="accessurl" type="xs:string"/>
	<xs:element name="accessdir" type="xs:string"/>
	<xs:element name="Required" type="xs:string"/>
	<xs:element name="Documentation" type="xs:string"/>
        <xs:element name="Default">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="clireplacement" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Datatype" type="xs:string"/>
    <xs:element name="CliMapping" type="xs:string"/>
    <xs:element name="OutFileName" type="xs:string"/>
</xs:schema>

=== cai880210/iif-toolwrapper/examples/abbyyocrcloud.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>abbyyocrcloud</id>
    <name>Abbyy OCR Cloud</name>
    <homepage>http://ocrsdk.com/</homepage>
    <version></version>
    <installation>
        <os type="linux">
            Not applicable. You need to have the {ABBYY_APPID} and {ABBYY_PWD} environment variables defined!
        </os>
        <os type="windows">
            Not applicable. You need to have the {ABBYY_APPID} and {ABBYY_PWD} environment variables defined!
        </os>
    </installation>
    <services>
        <service sid="1" name="AbbyyOcrCloud" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for text recognition using Abbyy OCR cloud</description>
            <operations>
                <operation oid="1" name="ocr">
                    <description>Perform text recognition on input image file</description>
                    <!--
                    Usage:
                    cloud_recognize <input> <output> [-l language] [-f txt|rtf|docx|xlsx|pptx|pdfSearchable|pdfTextAndImages|xml]
		    -       Note that you need to have the {ABBYY_APPID} and {ABBYY_PWD} environment variables defined!

                    Where:
                    <input>     Input image file
                    <output>    Output file
                    <language>  Language used in recognition
		            <txt|rtf|docx|xlsx|pptx|pdfSearchable|pdfTextAndImages|xml> Output format
                    -->
                    <command>sh cloud_recognize.sh ${input} ${output} -l ${language} -f ${format}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>infile</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.tif</Default>
                        </input>
                        <input name="language">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>language</CliMapping>
                            <Documentation>Language used in recognition process</Documentation>
                            <Default>German</Default>
                            <Restriction>
				                <Value>Bulgarian</Value>
                                <Value>Catalan</Value>
                                <Value>Croatian</Value>
                                <Value>Czech</Value>
                                <Value>Danish</Value>
                                <Value>Dutch</Value>
                                <Value>English</Value>
                                <Value>Estonian</Value>
                                <Value>Finnish</Value>
                                <Value>French</Value>
                                <Value>German</Value>
                                <Value>Greek</Value>
                                <Value>Hungarian</Value>
                                <Value>Italian</Value>
                                <Value>Latin</Value>
                                <Value>Latvian</Value>
                                <Value>Lithuanian</Value>
                                <Value>Norwegian</Value>
                                <Value>OldEnglish</Value>
                                <Value>OldFrench</Value>
                                <Value>OldGerman</Value>
                                <Value>OldItalian</Value>
                                <Value>OldSpanish</Value>
                                <Value>Polish</Value>
                                <Value>PortugueseStandard</Value>
                                <Value>Romanian</Value>
                                <Value>Russian</Value>
                                <Value>SerbianCyrillic</Value>
                                <Value>SerbianLatin</Value>
                                <Value>Slovak</Value>
                                <Value>Slovenian</Value>
                                <Value>Spanish</Value>
                                <Value>Swedish</Value>
                                <Value>Turkish</Value>
                                <Value>Ukrainian</Value>
                            </Restriction>
                        </input>
			            <input name="format">
                            <Datatype>xsd:string</Datatype>
                            <Required>true</Required>
                            <CliMapping>format</CliMapping>
                            <Documentation>Output file format</Documentation>
                            <Default>txt</Default>
                            <Restriction>
                                <Value>txt</Value>
                                <Value>rtf</Value>
				                <Value>docx</Value>
				                <Value>xlsx</Value>
				                <Value>pptx</Value>
				                <Value>pdfSearchable</Value>
				                <Value>pdfTextAndImages</Value>
				                <Value>xml</Value>
                            </Restriction>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to output file</Documentation>
                            <Extension>txt</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/wordevaluation.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>wordevaluation</id>
    <name>INL Word Evaluation</name>
    <homepage>http://www.digitisation.eu/</homepage>
    <version>1-0</version>
    <installation>
        <os type="linux">
            Fully supported through Java.
        </os>
        <os type="windows">
            Fully supported through Java.
        </os>
    </installation>
    <services>
        <service sid="1" name="WordEvaluation" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Service for evaluating word accuracy of OCR vs ground truth in PAGE format</description>
            <operations>
                <operation oid="1" name="wordEval">
                    <description>Evaluate OCR word accurracy</description>
                    <!--
                    Usage:
                    java -jar wordevaluation.jar -o <output> <groundtruth> <ocr>

                    Where:
                    <output>        Write output file
                    <groundtruth>   Ground truth file in PAGE format
                    <ocr>           OCR result file in PAGE format
                    -->
                    <command>java -jar wordevaluation.jar -o ${output} ${groundtruth} ${ocrresult}</command>
                    <inputs>
                        <input name="groundtruth">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>groundtruth</CliMapping>
                            <Documentation>URL reference to ground truth file in PAGE format</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/groundtruth.xml</Default>
                        </input>
                        <input name="ocrresult">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>ocrresult</CliMapping>
                            <Documentation>URL reference to OCR result file in PAGE format</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/ocr.xml</Default>
                        </input>
                        <input name="evaluationId">
                            <Datatype>xsd:string</Datatype>
                            <Required>false</Required>
                            <CliMapping></CliMapping>
                            <Documentation>Evaluation ID</Documentation>
                            <Default>Default_Evaluation_ID</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="output">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>output</CliMapping>
                            <Documentation>URL reference to statistics output file</Documentation>
                            <Extension>xml</Extension>
                            <OutFileName>output.xml</OutFileName>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/abbyy10binarisation.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>fre10binarisation</id>
    <name>ABBYY FineReader Engine 10 Binarisation</name>
    <homepage>http://www.digitisation.eu/tools/browse/image-enhancement/binarisation-and-colour-reduction/abbyy-fr-binarisation/</homepage>
    <version>10</version>
    <installation>
        <os type="linux">
            Not currently supported.
        </os>
        <os type="windows">
            Requires installation of the ABBYY FineReader Engine 10 SDK. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
    </installation>
    <services>
        <service sid="1" name="FineReader10Binarisation" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for binarisation using Abbyy Fine Reader Engine 10</description>
            <operations>
                <operation oid="1" name="binarise">
                    <description>Binarise document image file using FineReader 10</description>
                    <!--
                    Usage:
                    Abbyy10Binarisation.exe -if <in> -of <out>

                    Where:
                    <in>    Input image file
                    <out>   Bitonal output image file
                    -->
                    <command>Abbyy10Binarisation.exe -if ${infile} -of ${outfile}</command>
                    <inputs>
                        <input name="infile">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>infile</CliMapping>
                            <Documentation>URL reference to input image file</Documentation>
                            <Default>https://github.com/impactcentre/iif-testfiles/raw/master/testfiles/image.tif</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="outfile">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outfile</CliMapping>
                            <Documentation>URL reference to output bitonal image file</Documentation>
                            <Extension>tif</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
	        Full path to the directory where the tool has been installed.
	        THE PATH MUST NOT CONTAIN WHITESPACES!
	        If you want to use backslashes (\) then you must repeat them twice,
	        e.g. c:\\foo\\bar
	        or you can use just slashes,
	        e.g. c:/foo/bar
	        -->
            <toolsbasedir>C:\\FRE10BIN\\</toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>

=== cai880210/iif-toolwrapper/examples/mallet.xml
<?xml version="1.0" encoding="UTF-8"?>
<toolspec model="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/main/resources/toolspec.xsd">
    <id>mallet</id>
    <name>MAchine Learning for LanguagE Toolkit</name>
    <homepage>http://mallet.cs.umass.edu/</homepage>
    <version>2-0-7</version>
    <installation>
        <os type="linux">
            Binaries for Linux are available from the project homepage. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
        </os>
        <os type="windows">
            Binaries for Windows are available from the project homepage. THE FULL PATH TO THE EXECUTABLE MUST NOT CONTAIN WHITESPACES!
            The environment variable MALLET_HOME needs to be defined.
        </os>
    </installation>
    <services>
        <service sid="1" name="Mallet" type="migrate" servicepackage="eu.impact_project.iif.service" contextpathprefix="/impactservices">
            <description>Services for topic modelling using Mallet</description>
            <operations>
                <operation oid="1" name="mallet">
                    <description>Topic modelling</description>
                    <!--
                    Usage:
                    bin\mallet[.bat] [options] <input> <outputs>

                    Where:
                    [options] 	optional command line parameters
                    <input> 	input data in MALLET format
                    <outputs> 	topic modelling results

                    For more documentation on available command line parameters, see
                    http://mallet.cs.umass.edu/topics.php
                    -->
                    <command>/bin/mallet train-topics  --num-topics 20 --optimize-interval 20 --input ${input} --output-state ${outstate} --output-topic-keys ${outkeys} --output-doc-topics ${outtopics}</command>
                    <inputs>
                        <input name="input">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>true</Required>
                            <CliMapping>input</CliMapping>
                            <Documentation>URL reference to input file</Documentation>
                            <Default>http://github.com/impactcentre/iif-testfiles/raw/master/testfiles/tutorial.mallet</Default>
                        </input>
                    </inputs>
                    <outputs>
                        <output name="outstate">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outstate</CliMapping>
                            <Documentation>URL reference to topic model output</Documentation>
                            <Extension>gz</Extension>
                        </output>
			            <output name="outkeys">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outkeys</CliMapping>
                            <Documentation>URL reference to topic keys output</Documentation>
                            <Extension>txt</Extension>
                        </output>
			            <output name="outtopics">
                            <Datatype>xsd:anyURI</Datatype>
                            <Required>false</Required>
                            <CliMapping>outtopics</CliMapping>
                            <Documentation>URL reference to topic composition output</Documentation>
                            <Extension>txt</Extension>
                        </output>
                    </outputs>
                </operation>
            </operations>
            <deployto>
                <deployref default="true" ref="local"/>
            </deployto>
        </service>
    </services>
    <deployments>
        <deployment id="local">
            <identifier>http://localhost:8080/impact/instances/tomcat1</identifier>
            <host>localhost</host>
            <ports>
                <port type="http">8080</port>
                <port type="https">8043</port>
            </ports>
            <manager>
                <user>tomcat</user>
                <password>tomcat</password>
                <path>manager</path>
            </manager>
            <!--
            Full path to the directory where the tool has been installed.
            THE PATH MUST NOT CONTAIN WHITESPACES!
            If you want to use backslashes (\) then you must repeat them twice,
            e.g. c:\\foo\\bar
            or you can use just slashes,
            e.g. c:/foo/bar
            -->
            <toolsbasedir></toolsbasedir>
            <dataexchange>
                <accessdir>../webapps/ROOT/impact/tmp/</accessdir>
                <accessurl>http://localhost:8080/impact/tmp/</accessurl>
            </dataexchange>
        </deployment>
    </deployments>
</toolspec>
